{{ range $saName, $saConfig := .Values.serviceAccounts }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $saName }}
  annotations:
    {{- range $key, $value := $saConfig.annotations }}
    {{ $key }}: {{ $value }}
    {{- end }}
---
{{- end }}