# Default configMap
{{- if .Values.configMap }}
  apiVersion: v1
  kind: ConfigMap
  metadata:
    name: {{ .Release.Name }}-configmap
  data:
  {{- range $key, $value := .Values.configMap }}
    {{ $key }}: {{ $value }}
  {{- end }}
---
{{- end }}

# Deployment configMap
{{- range $appName, $appConfig := .Values.apps -}}
  {{- if $appConfig.volumes }}
    {{- range $appConfig.volumes }}
      {{- if .type.configMap }}
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: {{ $appName }}-configmap
      data:
        {{- range $key, $value := .configMapData }}
        {{ $key }}: |- {{ tpl $value $ }}
        {{- end }}
      {{- end }}
---
    {{- end }}
  {{- end }}
{{- end }}

# cronJob configMap
{{- range $scriptName, $scriptConfig := .Values.scripts }}
  apiVersion: v1
  kind: ConfigMap
  metadata:
    name: {{ $scriptName }}
  data:
    {{- range $key, $value := $scriptConfig }}
    {{ $key }}: |- 
      {{ tpl $value $ }}
    {{- end }}
{{- end }}

# job configMap
{{- range $jobName, $jobConfig := .Values.jobs -}}
  {{- if $jobConfig.volumes }}
    {{- range $jobConfig.volumes }}
      {{- if .type.configMap }}
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: {{ .type.configMap.name }}
      data:
        {{- range $key, $value := .configMapData }}
        {{ $key }}: |- {{ tpl $value $ }}
        {{- end }}
      {{- end }}
---
    {{- end }}
  {{- end }}
{{- end }}
