# Default configMap
{{- if .Values.configMap }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
data:
{{- range $key, $value := .Values.configMap }}
  {{ $key }}: {{ $value }}
{{- end }}
---
{{- end }}

# Deployment configMap
{{- range $appName, $appConfig := .Values.apps -}}
{{- if $appConfig.volumes }}
{{- range $appConfig.volumes }}
{{- if .type.configMap }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $appName }}-configmap
data:
  {{- range $key, $value := .configMapData }}
  {{ $key }}: |- {{ tpl $value $ }}
  {{- end }}
{{- end }}
---
{{- end }}
{{- end }}
{{- end }}

# cronJob configMap
{{- range $cronjobName, $cronjobConfig := .Values.cronjobs }}
{{- if $cronjobConfig.volumes }}
{{- range $cronjobConfig.volumes }}
{{- if .type.configMap }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .type.configMap.name }}
data:
{{- if isValidYAML .configMapData }}
  {{- range $key, $value := .configMapData }}
    {{ $key }}: |- {{ tpl $value $ }}
  {{- end }}
{{- else }}
  {{- range $key, $value := .configMapData }}
    {{ $key }}: |- {{ toJson $value }}
  {{- end }}
{{- end }}
{{- end }}
---
{{- end }}
{{- end }}
{{- end }}

{{- define "isValidYAML" }}
{{- $value := . }}
{{- try }}
{{- toYaml $value }}
{{- true }}
{{- catch }}
{{- false }}
{{- end }}
{{- end }}

# job configMap
{{- range $jobName, $jobConfig := .Values.jobs -}}
{{- if $jobConfig.volumes }}
{{- range $jobConfig.volumes }}
{{- if .type.configMap }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .type.configMap.name }}
data:
  {{- range $key, $value := .configMapData }}
  {{ $key }}: |- {{ tpl $value $ }}
  {{- end }}
{{- end }}
---
{{- end }}
{{- end }}
{{- end }}
