image: 831282932661.dkr.ecr.us-east-1.amazonaws.com/corecms
tag: 463078e75e8a80d19dea8855e91def2c3858b9b0
ingress:
  annotations:
    ingress.kubernetes.io/ssl-redirect: "true"
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
  hosts:
    - core.dev.iabbbops.org
  paths:
    - path: /
      pathType: Prefix
      servicePort: 3000
      serviceName: core-cms
externalSecret:
  secretStoreName: vault-backend
  refreshInterval: 1m
  type: vault
  secretPath: application
apps:
  core-cms:
    # serviceAccount: core-cms
    service:
      name: tcp
      type: ClusterIP
      port: 3000
      targetPort: 3000
      protocol: TCP
    resources:
      limits:
        memory: 1Gi
      requests:
        cpu: 300m
        memory: 1Gi
    volumes:
      - name: app-settings
        secret:
          secretName: core-cms
        mountPath: /app/appsettings.json
      - name: my-configmap-volume
        mountPath: /etc/scripts
        type:
          configMap:
            name: db-backups-scripts