{{- if .Values.ingress  }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ $.Release.Name }}
    product: {{ $.Release.Name }}
    {{- with $.Values.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- range $key, $value := .Values.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className | default "nginx" }}
  rules:
  {{- range .Values.ingress.hosts }}
    - host: {{ . | quote }}
      http:
        paths:
          {{- range $.Values.ingress.paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ .serviceName }}
                port:
                  number: {{ .servicePort }}
          {{- end }}
  {{- end }}
  tls:
  {{- if .Values.ingress.tls }}
    {{- toYaml .Values.ingress.tls | nindent 4 }}
  {{ else }}
    {{- range .Values.ingress.hosts }}
    - hosts:
        - {{ . | quote }}
      secretName: {{ . | replace "." "-" | replace "*" "star" }}-tls
    {{- end }}
  {{- end }}
---
{{- end }}