{{ range $appName, $appConfig := .Values.apps }}
{{- if $appConfig.hpa }}
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ if $.Values.pr }}{{ $.Release.Name }}-{{ $appName | trimPrefix $.Release.Name | trimPrefix "-" }}{{ else }}{{ $appName }}{{ end }}
  labels:
    app: {{ if $.Values.pr }}{{ $.Release.Name }}-{{ $appName | trimPrefix $.Release.Name | trimPrefix "-" }}{{ else }}{{ $appName }}{{ end }}
    product: {{ $.Release.Name }}
    {{- with $.Values.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  maxReplicas: {{ $appConfig.hpa.maxReplicas }}
  minReplicas: {{ $appConfig.hpa.minReplicas }}
  scaleTargetRef:
    apiVersion: {{ if $appConfig.rollout }}argoproj.io/v1alpha1{{ else }}apps/v1{{ end }}
    kind: {{ if $appConfig.rollout }}Rollout{{ else }}Deployment{{ end }}
    name: {{ if $.Values.pr }}{{ $.Release.Name }}-{{ $appName | trimPrefix $.Release.Name | trimPrefix "-" }}{{ else }}{{ $appName }}{{ end }}
  metrics:
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: {{ $appConfig.hpa.memoryTarget }}
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ $appConfig.hpa.cpuTarget }}
---
{{- end }}
{{- end }}