{{- range $cronjobName, $cronjobConfig := .Values.cronjobs }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ $cronjobName }}
  labels:
    app: {{ $cronjobName }}
    product: {{ $.Release.Name }}
    {{- with $.Values.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  schedule: {{ $cronjobConfig.schedule | quote }}
  suspend: {{ $cronjobConfig.suspend | default "false" }}
  concurrencyPolicy: {{ $cronjobConfig.concurrencyPolicy | default "Replace" }}
  jobTemplate:
    metadata:
      name: {{ $cronjobName }}
      labels:
        app: {{ $cronjobName }}
        product: {{ $.Release.Name }}
        {{- with $.Values.labels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      backoffLimit: {{ $cronjobConfig.backoffLImit | default "0" }}
      template:
        metadata:
          labels:
            app: {{ $cronjobName }}
            product: {{ $.Release.Name }}
            {{- with $.Values.labels }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
        spec:
          {{- if eq $.Values.nodeType "spot" }}
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                - matchExpressions:
                  - key: cloud.google.com/gke-spot
                    operator: In
                    values:
                    - "true"
          tolerations:
            - effect: NoSchedule
              key: cloud.google.com/gke-spot
              operator: Equal
              value: "true"
          {{- end }}
          {{- if $cronjobConfig.serviceAccount }}
          serviceAccountName: {{ $cronjobConfig.serviceAccount }}
          {{- end }}
          {{- if $cronjobConfig.initContainers }}
          initContainers:
            {{- range $initContainer := $cronjobConfig.initContainers }}
            - name: {{ $initContainer.name }}
              image: {{ $initContainer.image }}{{ if $initContainer.tag }}:{{ $initContainer.tag }}{{ end }}
              {{- if $initContainer.command }}
              command:
                {{- range $initContainer.command }} 
                - {{ . | quote }}
                {{- end }}
              {{- end }}
              args:
                {{- range $initContainer.args }}
                - {{ . | quote -}}
                {{ end }}
              {{- if $cronjobConfig.volumes }}
              volumeMounts:
                {{- range $cronjobConfig.volumes }}
                - mountPath: {{ .mountPath }}
                  name: {{ .name }}
                {{- end }}
              {{- end }}
              env:
                {{- range $key, $value := $initContainer.env }}
                - name: {{ $key }}
                  value: {{ $value | quote }}
                {{- end }}
              envFrom:
                {{- if $initContainer.secrets }}
                - secretRef:
                    name: {{ $initContainer.name }}
                {{- end }}
                {{- if $.Values.secrets }}
                - secretRef:
                    name: {{ $.Release.Name }}
                {{- end }}
            {{- end }}
          {{- end }}
          containers:
          {{- range $container := $cronjobConfig.containers }}
            - name: {{ $container.name }}
              image: "{{ $.Values.image.repository }}/{{ if $cronjobConfig.imageName }}{{ $cronjobConfig.imageName }}
                                                      {{- else if $.Values.image.name }}{{ $.Values.image.name }}
                                                      {{- else }}{{ $container.name }}{{ end }}:
                                                      {{- if $container.tag }}{{ $container.tag }}
                                                      {{- else if $cronjobConfig.imageTag }}{{ $cronjobConfig.imageTag }}
                                                      {{- else }}{{ $.Values.image.tag }}{{ end }}"
              {{- if $container.command }}
              command:
                {{- range $container.command }} 
                - {{ . | quote }}
                {{- end }}
              {{- end }}
              args: 
                {{- range $container.args }}
                - {{ . | quote -}}
                {{ end }}
              {{- if $cronjobConfig.volumes }}
              volumeMounts:
                {{- range $cronjobConfig.volumes }}
                - mountPath: {{ .mountPath }}
                  name: {{ .name }}
                {{- end }}
              {{- end }}
              env:
                {{- range $key, $value := merge (default dict $cronjobConfig.env) (default dict $.Values.env) }}
                - name: {{ $key }}
                  value: {{ $value | quote }}
                {{- end }}
              envFrom:
                {{- if $container.secrets }}
                - secretRef:
                    name: {{ $container.name }}
                {{- end }}
                {{- if $.Values.secrets }}
                - secretRef:
                    name: {{ $.Release.Name }}
                {{- end }}
            {{- end }}
          {{- if $cronjobConfig.volumes }}
          volumes:
            {{- range $cronjobConfig.volumes }}
            - name: {{ .name }}
              {{- with .type }}
                {{- toYaml . | nindent 14 }}
              {{- end }}
            {{- end }}
          {{- end }}
          restartPolicy: {{ $cronjobConfig.restartPolicy | default "Never"}}
---
{{- end }}