{{- range $cronjobName, $cronjobConfig := .Values.cronjobs }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ $cronjobName }}
  labels:
    app: {{ $cronjobName }}
    product: {{ $.Release.Name }}
    {{- with $.Values.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  schedule: {{ $cronjobConfig.schedule | quote }}
  suspend: {{ $cronjobConfig.suspend | default "false" }}
  concurrencyPolicy: {{ $cronjobConfig.concurrencyPolicy | default "Replace" }}
  jobTemplate:
    metadata:
      name: {{ $cronjobName }}
      labels:
        app: {{ $cronjobName }}
        product: {{ $.Release.Name }}
        {{- with $.Values.labels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      backoffLimit: {{ $cronjobConfig.backoffLImit | default "0" }}
      template:
        metadata:
          labels:
            app: {{ $cronjobName }}
            product: {{ $.Release.Name }}
            {{- with $.Values.labels }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
        spec:
          {{- if eq $.Values.nodeType "spot" }}
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                - matchExpressions:
                  - key: cloud.google.com/gke-spot
                    operator: In
                    values:
                    - "true"
          tolerations:
            - effect: NoSchedule
              key: cloud.google.com/gke-spot
              operator: Equal
              value: "true"
          {{- end }}
          {{- if $cronjobConfig.serviceAccount }}
          serviceAccountName: {{ $cronjobConfig.serviceAccount }}
          {{- end }}
          {{- if $cronjobConfig.initContainers }}
          initContainers:
            {{- range $initContainer := $cronjobConfig.initContainers }}
            - name: {{ $initContainer.name }}
              image: "{{- $initContainer.image | default $cronjobConfig.image | default $.Values.image }}:{{- $initContainer.tag | default $cronjobConfig.tag | default $.Values.tag }}"
              imagePullPolicy: "{{- $initContainer.imagePullPolicy | default $cronjobConfig.imagePullPolicy | default $.Values.imagePullPolicy }}"
              {{- if $initContainer.command }}
              command:
                {{- range $initContainer.command }} 
                - {{ . | quote }}
                {{- end }}
              {{- end }}
              args:
                {{- range $initContainer.args }}
                - {{ . | quote -}}
                {{ end }}
              {{- with $cronjobConfig.volumeMounts }}
              volumeMounts:
                {{- toYaml . | nindent 16  }}
              {{- end }}
              env:
                {{- range $key, $value := $initContainer.env }}
                - name: {{ $key }}
                  value: {{ $value | quote }}
                {{- end }}
              envFrom:
                {{- if $initContainer.secrets }}
                - secretRef:
                    name: {{ $initContainer.name }}
                {{- end }}
                {{- if $.Values.secrets }}
                - secretRef:
                    name: {{ $.Release.Name }}
                {{- end }}
            {{- end }}
          {{- end }}
          containers:
          {{- range $container := $cronjobConfig.containers }}
            - name: {{ $container.name }}
              {{- if $container.image }}
              image: "{{- $container.image | default $cronjobConfig.image | default $.Values.image }}:{{- $container.tag | default $cronjobConfig.tag | default $.Values.tag }}"
              imagePullPolicy: "{{- $container.imagePullPolicy | default $cronjobConfig.imagePullPolicy | default $.Values.imagePullPolicy }}"
              {{- else }}
              image: "{{ $.Values.image }}:{{ $.Values.tag }}"
              imagePullPolicy: "{{ $.Values.imagePullPolicy }}"
              {{- end }}
              {{- if $container.command }}
              command:
                {{- range $container.command }} 
                - {{ . | quote }}
                {{- end }}
              {{- end }}
              args: 
                {{- range $container.args }}
                - {{ . | quote -}}
                {{ end }}
              {{- with $container.resources }}
              resources:
                {{- toYaml . | nindent 16 }}
              {{- end }}
              {{- with $cronjobConfig.volumeMounts }}
              volumeMounts:
                {{- toYaml . | nindent 16 }}
              {{- end }}
              env:
                {{- range $key, $value := merge (default dict $cronjobConfig.env) (default dict $.Values.env) (default dict $container.env) }}
                - name: {{ $key }}
                  value: {{ $value | quote }}
                {{- end }}
              envFrom:
                {{- if $container.secrets }}
                - secretRef:
                    name: {{ $container.name }}
                {{- end }}
                {{- if $.Values.secrets }}
                - secretRef:
                    name: {{ $.Release.Name }}
                {{- end }}
            {{- end }}
          {{- with $cronjobConfig.volumes }}
          volumes:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          restartPolicy: {{ $cronjobConfig.restartPolicy | default "Never"}}
---
{{- end }}