{{- range $appName, $appConfig := .Values.apps }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ if $.Values.pr }}{{ $.Release.Name }}-{{ $appName | trimPrefix $.Release.Name | trimPrefix "-" }}{{ else }}{{ $appName }}{{ end }}
  labels:
    app: {{ if $.Values.pr }}{{ $.Release.Name }}-{{ $appName | trimPrefix $.Release.Name | trimPrefix "-" }}{{ else }}{{ $appName }}{{ end }}
    product: {{ $.Release.Name }}
    {{- with $.Values.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: {{ if $.Values.pr }}{{ $.Release.Name }}-{{ $appName | trimPrefix $.Release.Name | trimPrefix "-" }}{{ else }}{{ $appName }}{{ end }}
  template:
    metadata:
      labels:
        app: {{ if $.Values.pr }}{{ $.Release.Name }}-{{ $appName | trimPrefix $.Release.Name | trimPrefix "-" }}{{ else }}{{ $appName }}{{ end }}
        product: {{ $.Release.Name }}
        {{- with $.Values.labels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      annotations:
        {{- if $appConfig.secrets }}
        secret.reloader.stakater.com/reload: {{ if $.Values.pr }}{{ $.Release.Name }}-{{ $appName | trimPrefix $.Release.Name | trimPrefix "-" }}{{ else }}{{ $appName }}{{ end }}
        {{- end }}
        {{- if $.Values.secrets }}
        secret.reloader.stakater.com/reload: {{ $.Release.Name }}
        {{- end }}
    spec:
      {{- if eq $.Values.nodeType "spot" }}
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: cloud.google.com/gke-spot
                operator: In
                values:
                - "true"
      tolerations:
        - effect: NoSchedule
          key: cloud.google.com/gke-spot
          operator: Equal
          value: "true"
      {{- end }}
      {{- if $appConfig.serviceAccount }}
      serviceAccountName: {{ $appConfig.serviceAccount }}
      {{- end }}
      {{- if $appConfig.initContainers }}
      initContainers:
        {{- range $initContainerName, $initContainerConfig  := $appConfig.initContainers }}
        - name: {{ $initContainerName }}
          image: "{{- $initContainerConfig.image | default $appConfig.image | default $.Values.image }}:{{- $initContainerConfig.tag | default $appConfig.tag | default $.Values.tag }}"
          imagePullPolicy: "{{- $initContainerConfig.imagePullPolicy | default $appConfig.imagePullPolicy | default $.Values.imagePullPolicy }}"
          {{- if $initContainerConfig.command }}
          command:
            {{- range $initContainerConfig.command }} 
            - {{ . | quote }}
            {{- end }}
          {{- end }}
          args:
            {{- range $initContainerConfig.args }}
            - {{ . | quote -}}
            {{ end }}
          {{- if $appConfig.volumes }}
          volumeMounts:
            {{- range $appConfig.volumes }}
            - mountPath: {{ .mountPath }}
              name: {{ .name }}
            {{- end }}
          {{- end }}
          env:
            {{- range $key, $value := $initContainerConfig.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          envFrom:
            {{- if $initContainerConfig.secrets }}
            - secretRef:
                name: {{ $initContainerName }}
            {{- end }}
            {{- if $.Values.secrets }}
            - secretRef:
                name: {{ $.Release.Name }}
            {{- end }}
        {{- end }}
      {{- end }}
      containers:
        - name: {{ $appName }}
          image: "{{- $appConfig.image | default $.Values.image }}:{{- $appConfig.tag | default $.Values.tag }}"
          imagePullPolicy: "{{- $appConfig.imagePullPolicy | default $.Values.imagePullPolicy }}"
          {{- if $appConfig.command }}
          command: {{ $appConfig.command }}
            {{- range $appConfig.command }} 
            - {{ . | quote }}
            {{- end }}
          {{- if $appConfig.args }}
          args:
            {{- range $appConfig.args }}
            - {{ . }}
            {{- end }}
          {{- end }}
          {{- if $appConfig.service }}
          ports:
            - name: {{ $appConfig.service.name }}
              containerPort: {{ $appConfig.service.port }}
              protocol: {{ $appConfig.service.protocol }}
          {{- end }}
          {{- with $appConfig.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          env:
            {{- range $key, $value := merge (default dict $appConfig.env) (default dict $.Values.env) }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          envFrom:
            {{- if $appConfig.secrets }}
            - secretRef:
                name: {{ if $.Values.pr }}{{ $.Release.Name }}-{{ $appName | trimPrefix $.Release.Name | trimPrefix "-" }}{{ else }}{{ $appName }}{{ end }}
            {{- end }}
            {{- if $.Values.secrets }}
            - secretRef:
                name: {{ $.Release.Name }}
            {{- end }}
          {{- with $appConfig.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- if $appConfig.volumes }}
          volumeMounts:
            {{- range $appConfig.volumes }}
            - mountPath: {{ .mountPath }}
              name: {{ .name }}
            {{- end }}
          {{- end }}    
      {{- if $appConfig.volumes }}
      volumes:
        {{- range $appConfig.volumes }}
        - name: {{ .name }}
          {{- with .type }}
            {{- toYaml . | nindent 10 }}
          {{- end }}
        {{- end }}
      {{- end }}    
---
{{- end }}