{{- range $jobName, $jobConfig := .Values.jobs }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ $jobName }}-{{ $.Values.image.tag }}
spec:
  template:
    spec:
      {{- if eq $.Values.nodeType "spot" }}
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: cloud.google.com/gke-spot
                operator: In
                values:
                - "true"
      tolerations:
        - effect: NoSchedule
          key: cloud.google.com/gke-spot
          operator: Equal
          value: "true"
      {{- end }}
      {{- if $jobConfig.serviceAccount }}
      serviceAccountName: {{ $jobConfig.serviceAccount }}
      {{- end }}
      containers:
        - name: {{ $.Release.Name }}-{{ $jobName }}
          image: {{ if $jobConfig.image }}
                    {{- $jobConfig.image.repository }}/{{ $jobConfig.imageName }}:{{ $jobConfig.image.tag }}
                  {{- else }}
                    {{- $.Values.image.repository }}/{{ $.Values.image.name }}:{{ $.Values.image.tag }}
                  {{- end }}
          {{- if $jobConfig.command }}
          command: 
            {{- range $jobConfig.command }}
            - {{ . | quote}}
            {{- end }}
          {{- end }}
          {{- if $jobConfig.args | quote }}
          args:
            {{- range $jobConfig.args }}
            - {{ . }}
            {{- end }}
          {{- end }}
          env:
            {{- range $key, $value := $jobConfig.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          envFrom:
            {{- if $jobConfig.secrets }}
            - secretRef:
                name: {{ $jobName }}
            {{- end }}
            {{- if $.Values.secrets }}
            - secretRef:
                name: {{ $.Release.Name }}
            {{- end }}
      restartPolicy: Never      
---
{{- end }}